python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\0.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\1.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\2.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\3.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\4.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\5.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\6.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\7.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\8.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\9.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\10.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\11.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\12.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\13.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\14.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\15.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\16.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\17.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\18.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\19.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test
python train.py --image G:\DL_Final\Mask_RCNN\dataset\test\0103528\image\20.tif  --weights G:\DL_Final\Mask_RCNN\PeritonealHemorrhageDetection\weight --logs logs --classnum 2 test